[package]
name = "sqlsherlock"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.13.2"
diesel = "1.4.3"
dotenv = "0.15.0"
failure = "0.1.6"
itertools = "0.8.1"
structopt = "0.3.3"

[features]
default = ["mysql", "postgres", "sqlite"]
mysql = ["diesel/mysql"]
postgres = ["diesel/postgres"]
sqlite = ["diesel/sqlite"]

[profile.release]
lto = true
panic = "abort"
