[licenses]
allow = [
    "MPL-2.0",
    "OpenSSL",
]
allow-osi-fsf-free = "both"

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[bans]
skip = [
    { name = "idna", version = "=0.1.5" },
    { name = "itoa", version = "=0.4.8" },
    { name = "percent-encoding", version = "=1.0.1" },
    { name = "url", version = "=1.7.2" },
]
